
--------------------
Timestamp: 2024-11-24 21:55:40,160
Level: ERROR
Message: Scraping data failed,potentially due to invalid symbol: FCRX
--------------------
Traceback (most recent call last):
  File "app\event_handlers\focus_guru_scrape_handlers.py", line 22, in scrape_focus_guru_data
  File "pandas\io\html.py", line 1240, in read_html
  File "pandas\io\html.py", line 1003, in _parse
  File "pandas\io\html.py", line 983, in _parse
  File "pandas\io\html.py", line 249, in parse_tables
  File "pandas\io\html.py", line 598, in _parse_tables
ValueError: No tables found

--------------------
Timestamp: 2024-11-24 21:55:40,161
Level: ERROR
Message: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\models\app_tabs\auto_stock_search.py", line 52, in run
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 21:58:09,865
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 21:58:09,865
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:00:32,726
Level: ERROR
Message: Error obtaining interest coverage: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 57, in verify_interest_coverage_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:00:32,726
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:00:32,727
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:06:32,305
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:08:19,181
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:08:19,181
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:12:11,630
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:12:11,630
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:12:11,630
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:14:15,746
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:14:15,746
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:18:49,084
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:20:05,363
Level: ERROR
Message: Error obtaining interest coverage: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 57, in verify_interest_coverage_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:20:05,364
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:20:05,364
Level: ERROR
Message: Error obtaining P/S: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 123, in verify_price_to_sales_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:20:05,364
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:22:40,165
Level: ERROR
Message: Error obtaining roe: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 74, in verify_roe
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:22:40,166
Level: ERROR
Message: Error obtaining roa: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 82, in verify_roa
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:22:40,166
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:22:40,166
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:25:32,454
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:25:32,455
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:28:06,752
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:33:36,085
Level: ERROR
Message: Error obtaining interest coverage: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 57, in verify_interest_coverage_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:33:36,085
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:33:36,085
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:36:12,388
Level: ERROR
Message: Error obtaining roe: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 74, in verify_roe
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:36:12,388
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:36:12,388
Level: ERROR
Message: Error obtaining P/B: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 131, in verify_price_to_book_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:37:49,129
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:37:49,129
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:39:10,699
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:42:20,228
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:45:04,483
Level: ERROR
Message: Error obtaining debt to equity: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 41, in verify_debt_to_equity_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:45:04,483
Level: ERROR
Message: Error obtaining ebitda: '<' not supported between instances of 'NoneType' and 'float'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 49, in verify_debt_to_ebitda_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'float'

--------------------
Timestamp: 2024-11-24 22:45:04,483
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:46:36,601
Level: ERROR
Message: Financial Strengths failed is missing Cash-To-Debt: could not convert string to float: 'No Debt'
--------------------
Traceback (most recent call last):
  File "app\event_handlers\focus_guru_scrape_handlers.py", line 55, in financial_strengths
ValueError: could not convert string to float: 'No Debt'

--------------------
Timestamp: 2024-11-24 22:46:36,606
Level: ERROR
Message: Error obtaining cash to debt: '>' not supported between instances of 'NoneType' and 'float'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 33, in varify_cash_to_debt_ratio
TypeError: '>' not supported between instances of 'NoneType' and 'float'

--------------------
Timestamp: 2024-11-24 22:46:36,606
Level: ERROR
Message: Error obtaining debt to equity: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 41, in verify_debt_to_equity_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:46:36,606
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:46:36,607
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:49:12,950
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:50:52,694
Level: ERROR
Message: Error obtaining cash to debt: '>' not supported between instances of 'NoneType' and 'float'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 33, in varify_cash_to_debt_ratio
TypeError: '>' not supported between instances of 'NoneType' and 'float'

--------------------
Timestamp: 2024-11-24 22:50:52,695
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:50:52,695
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:52:15,562
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:54:22,433
Level: ERROR
Message: Error obtaining interest coverage: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 57, in verify_interest_coverage_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:54:22,433
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:54:22,433
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:57:10,112
Level: ERROR
Message: Error obtaining interest coverage: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 57, in verify_interest_coverage_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:57:10,112
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 22:57:10,112
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:00:04,874
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:03:52,779
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:03:52,780
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:06:41,434
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:06:41,435
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:07:52,335
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:09:14,924
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:09:14,924
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:11:35,040
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:12:56,116
Level: ERROR
Message: Scraping data failed,potentially due to invalid symbol: FGBIP
--------------------
Traceback (most recent call last):
  File "app\event_handlers\focus_guru_scrape_handlers.py", line 22, in scrape_focus_guru_data
  File "pandas\io\html.py", line 1240, in read_html
  File "pandas\io\html.py", line 1003, in _parse
  File "pandas\io\html.py", line 983, in _parse
  File "pandas\io\html.py", line 249, in parse_tables
  File "pandas\io\html.py", line 598, in _parse_tables
ValueError: No tables found

--------------------
Timestamp: 2024-11-24 23:12:56,117
Level: ERROR
Message: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\models\app_tabs\auto_stock_search.py", line 52, in run
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:15:38,214
Level: ERROR
Message: Error obtaining interest coverage: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 57, in verify_interest_coverage_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:15:38,214
Level: ERROR
Message: Error obtaining roe: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 74, in verify_roe
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:15:38,214
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:15:38,214
Level: ERROR
Message: Error obtaining P/B: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 131, in verify_price_to_book_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:15:38,214
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:18:01,225
Level: ERROR
Message: Error obtaining interest coverage: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 57, in verify_interest_coverage_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:18:01,225
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:18:01,226
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:20:00,940
Level: ERROR
Message: Scraping data failed,potentially due to invalid symbol: FGFPP
--------------------
Traceback (most recent call last):
  File "app\event_handlers\focus_guru_scrape_handlers.py", line 22, in scrape_focus_guru_data
  File "pandas\io\html.py", line 1240, in read_html
  File "pandas\io\html.py", line 1003, in _parse
  File "pandas\io\html.py", line 983, in _parse
  File "pandas\io\html.py", line 249, in parse_tables
  File "pandas\io\html.py", line 598, in _parse_tables
ValueError: No tables found

--------------------
Timestamp: 2024-11-24 23:20:00,941
Level: ERROR
Message: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\models\app_tabs\auto_stock_search.py", line 52, in run
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:22:45,032
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:22:45,032
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:25:46,704
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:25:46,704
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:28:10,677
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:28:10,677
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:30:20,535
Level: ERROR
Message: Scraping data failed,potentially due to invalid symbol: FGN
--------------------
Traceback (most recent call last):
  File "app\event_handlers\focus_guru_scrape_handlers.py", line 22, in scrape_focus_guru_data
  File "pandas\io\html.py", line 1240, in read_html
  File "pandas\io\html.py", line 1003, in _parse
  File "pandas\io\html.py", line 983, in _parse
  File "pandas\io\html.py", line 249, in parse_tables
  File "pandas\io\html.py", line 598, in _parse_tables
ValueError: No tables found

--------------------
Timestamp: 2024-11-24 23:30:20,536
Level: ERROR
Message: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\models\app_tabs\auto_stock_search.py", line 52, in run
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:31:48,989
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:31:48,989
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:36:46,456
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:39:25,293
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:41:12,470
Level: ERROR
Message: Error obtaining roe: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 74, in verify_roe
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:41:12,470
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:41:12,470
Level: ERROR
Message: Error obtaining P/B: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 131, in verify_price_to_book_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:41:12,470
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:44:51,876
Level: ERROR
Message: Financial Strengths failed is missing Interest Coverage: could not convert string to float: 'No Debt'
--------------------
Traceback (most recent call last):
  File "app\event_handlers\focus_guru_scrape_handlers.py", line 55, in financial_strengths
ValueError: could not convert string to float: 'No Debt'

--------------------
Timestamp: 2024-11-24 23:44:51,879
Level: ERROR
Message: Error obtaining cash to debt: '>' not supported between instances of 'NoneType' and 'float'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 33, in varify_cash_to_debt_ratio
TypeError: '>' not supported between instances of 'NoneType' and 'float'

--------------------
Timestamp: 2024-11-24 23:44:51,879
Level: ERROR
Message: Error obtaining interest coverage: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 57, in verify_interest_coverage_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:44:51,880
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:44:51,880
Level: ERROR
Message: Error obtaining P/S: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 123, in verify_price_to_sales_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:44:51,880
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:46:56,091
Level: ERROR
Message: Financial Strengths failed is missing Interest Coverage: could not convert string to float: 'No Debt'
--------------------
Traceback (most recent call last):
  File "app\event_handlers\focus_guru_scrape_handlers.py", line 55, in financial_strengths
ValueError: could not convert string to float: 'No Debt'

--------------------
Timestamp: 2024-11-24 23:46:56,094
Level: ERROR
Message: Error obtaining cash to debt: '>' not supported between instances of 'NoneType' and 'float'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 33, in varify_cash_to_debt_ratio
TypeError: '>' not supported between instances of 'NoneType' and 'float'

--------------------
Timestamp: 2024-11-24 23:46:56,094
Level: ERROR
Message: Error obtaining interest coverage: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 57, in verify_interest_coverage_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:46:56,094
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:46:56,094
Level: ERROR
Message: Error obtaining P/S: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 123, in verify_price_to_sales_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:46:56,095
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:49:47,195
Level: ERROR
Message: Financial Strengths failed is missing Interest Coverage: could not convert string to float: 'No Debt'
--------------------
Traceback (most recent call last):
  File "app\event_handlers\focus_guru_scrape_handlers.py", line 55, in financial_strengths
ValueError: could not convert string to float: 'No Debt'

--------------------
Timestamp: 2024-11-24 23:49:47,198
Level: ERROR
Message: Error obtaining cash to debt: '>' not supported between instances of 'NoneType' and 'float'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 33, in varify_cash_to_debt_ratio
TypeError: '>' not supported between instances of 'NoneType' and 'float'

--------------------
Timestamp: 2024-11-24 23:49:47,198
Level: ERROR
Message: Error obtaining interest coverage: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 57, in verify_interest_coverage_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:49:47,199
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:49:47,199
Level: ERROR
Message: Error obtaining P/S: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 123, in verify_price_to_sales_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:49:47,199
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:51:05,538
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:53:27,846
Level: ERROR
Message: Profitability rank is missing ROE % : could not convert string to float: 'Neg. Equity'
--------------------
Traceback (most recent call last):
  File "app\event_handlers\focus_guru_scrape_handlers.py", line 89, in profitability_rank
ValueError: could not convert string to float: 'Neg. Equity'

--------------------
Timestamp: 2024-11-24 23:53:27,849
Level: ERROR
Message: Error obtaining roe: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 74, in verify_roe
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:53:27,849
Level: ERROR
Message: Error obtaining P/B: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 131, in verify_price_to_book_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:55:04,121
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:56:48,974
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:59:45,782
Level: ERROR
Message: Error obtaining cash to debt: '>' not supported between instances of 'NoneType' and 'float'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 33, in varify_cash_to_debt_ratio
TypeError: '>' not supported between instances of 'NoneType' and 'float'

--------------------
Timestamp: 2024-11-24 23:59:45,782
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-24 23:59:45,782
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-25 00:02:04,400
Level: ERROR
Message: Error obtaining debt to equity: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 41, in verify_debt_to_equity_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-25 00:03:28,866
Level: ERROR
Message: Error obtaining roic '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 90, in verify_roic
TypeError: '>' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-25 00:03:28,866
Level: ERROR
Message: Error obtaining peg: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 115, in verify_peg_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-25 00:03:28,866
Level: ERROR
Message: Error obtaining P/FCF: '<' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\automation\stock_analysis_utils\data_validators.py", line 139, in verify_price_to_free_cash_flow_ratio
TypeError: '<' not supported between instances of 'NoneType' and 'int'

--------------------
Timestamp: 2024-11-25 00:04:34,481
Level: ERROR
Message: HTTPSConnectionPool(host='www.gurufocus.com', port=443): Max retries exceeded with url: /stock/FIP/summary (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027C1BC4C2F0>: Failed to resolve 'www.gurufocus.com' ([Errno 11001] getaddrinfo failed)"))
--------------------
Traceback (most recent call last):
  File "urllib3\connection.py", line 199, in _new_conn
  File "urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 963, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 693, in connect
  File "urllib3\connection.py", line 206, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000027C1BC4C2F0>: Failed to resolve 'www.gurufocus.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.gurufocus.com', port=443): Max retries exceeded with url: /stock/FIP/summary (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027C1BC4C2F0>: Failed to resolve 'www.gurufocus.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\automation\focus_guru_automation_interactions.py", line 57, in analyse_focus_guru_scraped_data
  File "app\event_handlers\focus_guru_scrape_handlers.py", line 18, in scrape_focus_guru_data
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 700, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.gurufocus.com', port=443): Max retries exceeded with url: /stock/FIP/summary (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027C1BC4C2F0>: Failed to resolve 'www.gurufocus.com' ([Errno 11001] getaddrinfo failed)"))

--------------------
Timestamp: 2024-11-25 00:04:34,483
Level: ERROR
Message: '>' not supported between instances of 'NoneType' and 'int'
--------------------
Traceback (most recent call last):
  File "app\models\app_tabs\auto_stock_search.py", line 52, in run
TypeError: '>' not supported between instances of 'NoneType' and 'int'
